# Generated by Django 4.1.4 on 2023-01-02 05:12

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleInvitation',
            fields=[
                (
                    'invitation_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='organization.invitation',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
            bases=('organization.invitation',),
        ),
        migrations.CreateModel(
            name='ExampleMember',
            fields=[
                (
                    'member_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='organization.member',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
            bases=('organization.member',),
        ),
        migrations.CreateModel(
            name='ExampleOrganization',
            fields=[
                (
                    'organization_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='organization.organization',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
            bases=('organization.organization',),
        ),
        migrations.CreateModel(
            name='ExampleUser',
            fields=[
                (
                    'user_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
