# Generated by Django 4.1.4 on 2023-01-02 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name='uuid',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='created date-time'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, verbose_name='updated date-time'
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        default=None,
                        editable=False,
                        null=True,
                        verbose_name='deleted date-time',
                    ),
                ),
                (
                    'permission_level',
                    models.PositiveIntegerField(
                        choices=[
                            (0, 'anonymous'),
                            (20, 'guest'),
                            (40, 'staff'),
                            (60, 'manager'),
                            (80, 'owner'),
                            (100, 'admin'),
                        ],
                        default=20,
                        verbose_name='permission level',
                    ),
                ),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('expires_at', models.DateTimeField(verbose_name='expires date-time')),
                (
                    'status',
                    models.PositiveIntegerField(
                        choices=[
                            (1, 'pending'),
                            (2, 'accepted'),
                            (3, 'declined'),
                            (4, 'canceled'),
                            (5, 'expired'),
                        ],
                        default=1,
                        verbose_name='status',
                    ),
                ),
                (
                    'inviter',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='user who invites',
                    ),
                ),
            ],
            options={
                'verbose_name': 'invitation',
                'verbose_name_plural': 'invitations',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name='uuid',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='created date-time'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, verbose_name='updated date-time'
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        default=None,
                        editable=False,
                        null=True,
                        verbose_name='deleted date-time',
                    ),
                ),
                (
                    'permissions_policy',
                    models.JSONField(
                        default=None, null=True, verbose_name='permissions policy'
                    ),
                ),
                ('level', models.PositiveIntegerField(default=0, verbose_name='level')),
                (
                    'owner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='owner',
                    ),
                ),
                (
                    'super_organization',
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='sub_organization_set',
                        to='organization.organization',
                        verbose_name='super organization',
                    ),
                ),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name='uuid',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='created date-time'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, verbose_name='updated date-time'
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        default=None,
                        editable=False,
                        null=True,
                        verbose_name='deleted date-time',
                    ),
                ),
                (
                    'permission_level',
                    models.PositiveIntegerField(
                        choices=[
                            (0, 'anonymous'),
                            (20, 'guest'),
                            (40, 'staff'),
                            (60, 'manager'),
                            (80, 'owner'),
                            (100, 'admin'),
                        ],
                        default=20,
                        verbose_name='permission level',
                    ),
                ),
                (
                    'invitation',
                    models.OneToOneField(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to='organization.invitation',
                        verbose_name='invitation',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='organization.organization',
                        verbose_name='organization',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='user',
                    ),
                ),
            ],
            options={
                'verbose_name': 'member',
                'verbose_name_plural': 'members',
                'ordering': ('-permission_level', 'created_at'),
            },
        ),
        migrations.AddField(
            model_name='invitation',
            name='organization',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='organization.organization',
                verbose_name='organization',
            ),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(
                fields=('organization', 'user'), name='unique_organization_and_user'
            ),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(
                condition=models.Q(('status', 1)),
                fields=('organization', 'email'),
                name='unique_organization_and_email',
            ),
        ),
    ]
